# -*- coding: utf-8 -*-
"""Case Study.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k30r8UFhirg88UryLRVwJQt23EENWhXv
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

movie = pd.read_csv('netflix_titles.csv')
movie.head()

movie.tail()

movie.isna()

movie.describe()

movie.describe(include='all').transpose()

movie.info()

movie.isna().sum()

movie.nunique()

movie.drop(['director','cast'], axis=1, inplace=True)

movie.isna().sum()

movie['country'].mode()

movie['country'] = movie['country'].fillna(movie['country'].mode()[0])

movie.isna().sum()

n_rating = movie['rating'].isna()
n_rating

null_rating = movie[n_rating]
null_rating

rating_replacements = {
  67: 'TV-PG',
  2359: 'TV-14',
  3660: 'TV-MA',
  3736: 'TV-MA',
  3737: 'NR',
  3738: 'TV-MA',
  4323: 'TV-MA'
}

rating_replacements.items()

for id, rate in rating_replacements.items():
  movie.loc[id, 'rating']=rate

movie.isna().sum()

movie['date_added']=movie[['date_added']].replace(np.nan,'Not Added')

movie.isna().sum()

movie['release_year'].value_counts()

movie['release_year'].value_counts().index[0:15]

plt.figure(figsize=(10,6))
sb.set(style='whitegrid')
sb.countplot(data = movie, y='release_year', order=movie['release_year'].value_counts().index[0:15])

plt.title('Release Year', fontsize=12, fontweight='bold')
plt.xlabel('Total')
plt.ylabel('Year')

sb.countplot(x='type',data=movie, palette='rocket')

plt.figure(figsize=(12,9))
sb.countplot(data = movie, y='rating', palette='rocket', order=movie['rating'].value_counts().index[0:10])

movie['release_month']=movie['date_added'].apply(lambda x: x.lstrip().split(" ")[0])
movie.head()

plt.figure(figsize=(12,9))
plt.yticks(rotation=45)
sb.countplot(x='release_month', data=movie, order=movie['release_month'].value_counts().index[0:10])

