# -*- coding: utf-8 -*-
"""numeric.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12dmhGLHEtm2yV57l6nu6sUM6vVrjscu3
"""

a = 10
print(a)

b = 15
b

a

"""Shell Commands"""

!ls

!pwd

"""Magics"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np

# %timeit np.linalg.eigvals(np.random.rand(100,100))

np.random?

"""MARKDOWN

nama makanan | harga
----|----
nasi goreng | 2000
ayam | 7000
"""

import numpy as nm

[1,2,3]

"""[[1,2,3][4,5,6]]"""

[[1,2,3],[4,5,6]]

a = nm.array([1,2,3])
b = nm.array([(1,2,3),(4,5,6)])

print(a)
print(b)

"""ndarray : nama class sebuah numpy array"""

print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)

"""numpy array"""

nm.zeros((3,3))

nm.ones((3,3))

nm.arange(1,2,0.2)

nm.linspace(1,3,10)

nm.random.random((2,3))

"""indexing"""

data = np.arange(100, 200)
data

data[0]

fives = np.arange(0,100,5)
fives

data[fives]

data2 = data.reshape(25,4)
data2

data2[2]

data2[0,3] #baris,kolom

data2[-2,-3]

data2[:,2]

data2[2,:]

data2[1:4, 1:3]

"""mathematics"""

numbers = nm.random.random((5,5))
numbers

print(nm.amin(numbers))
print(nm.amax(numbers))
print(nm.average(numbers))
print(nm.sum(numbers))

nm.sqrt(numbers)

sample = np.arange(1,21)
sample

sample+sample

sample-sample

sample2 = np.arange(1, 100 , 5)
sample2

sample + sample2

matrix = nm.random.randint(1,50,20)
matrix

matrix = matrix.reshape(4,5)
matrix

matrix.transpose()

nm.dot(matrix, -1)

