# -*- coding: utf-8 -*-
"""visualisasi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uy3ybEryGr0LaxYX2Iu16p5rswDaol2K
"""

import matplotlib.pyplot as pp
import seaborn as sb

tips = sb.load_dataset('tips')
tips

tips.head()

tips.info()

tips.describe(include='all')

tips.describe(include='all').transpose()

sb.histplot(data=tips, x='sex')

sb.histplot(data=tips, x='sex', y='smoker')

sb.histplot(data=tips, x='sex', shrink=.8)

pp.title('Gender',size=16)
pp.show()

sb.histplot(data=tips, x='smoker', shrink=.8)

pp.title('smoker',size=16)
pp.show()

from scipy.stats import alpha
tips['total_bill'].hist(color='green',alpha=0.4)

pp.title('Bill Distribution', size=16)
pp.show()

sb.histplot(data=tips, x='total_bill')

sb.histplot(data=tips, x='total_bill', hue='sex')

sb.histplot(data=tips, x='sex', hue='smoker')

pp.figure(figsize=(10,6))
sb.histplot(data=tips, x='total_bill', hue='sex')

pp.title('Bill Distribution Based on Sex', size=12)
pp.show()

sb.boxplot(x='day',y='total_bill', data=tips)

sb.boxplot(x='time',y='tip',data=tips)

sb.boxplot(x='time',y='tip', data=tips, order=['Dinner','Lunch'])

sb.boxplot(x='day',y='tip', data=tips)

flight = sb.load_dataset('flights')
flight

flight.head()

flight.info()

flight.describe(include='all')

sb.lineplot(data=flight, x='year', y='passengers')

sb.lineplot(data=flight, x='month', y='passengers')

januari = flight.query("month == 'Jan'")
januari

sb.lineplot(data = januari, x='year', y='passengers')

sb.lineplot(data=flight, x='year', y='passengers', hue='month')

sb.scatterplot(data = tips, x='total_bill', y='tip')

sb.scatterplot(data = tips, x='total_bill', y='tip', hue='day')

pp.title('Total Bill vs Tip')
pp.show()

pp.figure(figsize=(10,6))
sb.scatterplot(data = tips, x='total_bill', y='tip', hue='day',style='time')

pp.title('Total Bill vs Tip', size=15)
pp.show()

